สรุป :
1.  NumPy เป็นคลังคําสั่งที่ให้บริการมากมายเกี่ยวกับการคํานวณทางวิทยาศาสตร์
    โดยมีที่เก็บข้อมูลที่เรียกว่า อาเรย์ n มิติ (ndarray) มีไว้เก็บข้อมูลเพื่อการประมวลผลที่มีประสิทธิภาพมากๆ
2.  อาเรย์มีลักษณะคล้ายลิสต์ แต่สร้างแล้วเปลี่ยนขนาดไม่ได้
3.  ค่าในอาเรย์ทุกช่องต้องเป็นประเภทเดียวกันทั้งหมด เช่น เป็น int ทุกช่อง หรือ float ทุกช่อง
    (ผสมกันไม่ได้ ถ้าเป็นลิสต์ผสมได้)
4.  เราสร้าง เวกเตอร์ ได้ด้วยอาเรย์ 1 มิติ และสร้าง เมทริกซ์ ได้ด้วยอาเรย์ 2 มิติ

1. type ของข้อมูล "ndarray: N-Dimensional array" อาร์เรย์หลายมิติ ถูกเก็บข้อมูลอย่างต่อเนื่องเเละประมวลผลได้อย่างมีประสิทธิภาพ

In [ ]:
import numpy as np
x = np.array([1,2,3]) #1 มิติ
print(x)
print(type(x)) 

[1 2 3]
<class 'numpy.ndarray'>


2. การหาขนาด/มิติ ในอาร์เรย์ โดยจะบอกขนาดของเเถวและคอลัมน์

In [ ]:
import numpy as np
b = np.array([[1,2,0],[3,4,6]])
print(b.shape) #(2,3)-->(Rows,Col) 
print(b.size) #(2,3)-->(Rows,Col)
print(type(b.size)) 


(2, 3)
6
<class 'int'>


3. เปลี่ยนค่าในเมทริกซ์ 

In [ ]:
import numpy as np
b = np.array([[1,2,0],[3,4,6]])
b[0,0] = 5  #เปลี่ยนเลข(1)-->(5)
print(b)

[[5 2 0]
 [3 4 6]]


4. การสร้างเมทริกซ์ 0

In [ ]:
import numpy as np
zeros= np.zeros((2,2))
print(zeros)

5. การสร้างเมทริกซ์เอกลักษณ์

In [ ]:
import numpy as np
identity = np.eye(5) #เปลี่ยนเลข(5)-->มิติ 5x5
print(identity)

6. เปลี่ยนทุกตัวเลขทุกตัวเป็นเลขตัวนั้น

In [ ]:
import numpy as np
six = np.full((3,3),6) #((Row,Col),เลข)
print(six)

7. สุ่มตัวเลขในเมทริกซ์

In [ ]:
import numpy as np
random = np.random.random((3,3))
print(random)

8. ค้นหาตำแหน่่งของข้อมูลในอาเรย์

In [ ]:
import numpy as np
a = np.array([2,3,4,5,1,2])
print(np.where(a%2==0)) #(array([0, 2, 5]),) >>> ตน.

9. การหาค่าเปอร์เซ็นไทล์ที่ 25, 50, เเละ 75 

In [ ]:
import numpy as np
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(data,50))
print(np.percentile(data,25,axis=0)) #axis = 0 แกนตั้ง
print(np.percentile(data,75))

10. การดำเนินการในเมทริกซ์ 
    รวมเมทริกซ์(sum), การคูณเมทริกซ์(prod),  Root(sqrt),
    ดีเทอร์มิเเนนท์(det),ฟังก์ชันผกผัน(inverse)

In [ ]:
import numpy as np
emma = np.array([[1,9,3],[3,4,0],[1,-5,0]])
ice = np.array([1,-3,0], float)
print(emma+ice)
print(emma.sum())
print(emma.prod())
print(np.sqrt(emma))
x = np.linalg.det(emma) #หา det ของเมทริกซ์
result = round(x)
print("det=",result )
in_ = (np.linalg.inv(emma)) #หา inverse ของเมทริกซ์
print("inverse=",in_)

11. การหาค่าเฉลี่ย, ส่วนเบี่ยงเบนมาตรฐาน(SD) , ความแปรปรวน(V=SD**2)

In [ ]:
import numpy as np

emma = np.array([[1,9,3],[3,4,0],[1,-5,0]])
print(emma.mean()) #ค่าเฉลี่ยของข้อมูล คือการเอาข้อมูลหลายๆค่ามาเฉลี่ย 
print(emma.std()) #ส่วนเบี่ยงเบนมาตรฐาน
print(emma.var()) #ค่าความแปรปรวน

12. การหาค่าสูงสุด,ต่ำสุด (max,min) แบ่งเปรียบเทียบตามแกน (หลัก:axis=0) (แถว:axis=1) 

In [ ]:
import numpy as np

emma = np.array([[1,9,3],[3,4,0],[1,-5,0]])
print(emma.max(axis=0)) #เทียบกันเองตามหลัก [3,9,3]
print(emma.max(axis=1)) #เทียบกันเองตามแถว [9,4,1]